//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Строка_заказа
    {
        public int Id_СоставаЗаказа { get; set; }
        public int id_блюда { get; set; }
        public Nullable<decimal> колличество_блюд { get; set; }
        public int id_Заказа { get; set; }
    
        public virtual Блюда Блюда { get; set; }
        public virtual Заказы Заказы { get; set; }
    }
}
